version: 2.1

executors:
  node-executor:
    machine:
      enabled: true  # Use CircleCI's default VM, no Docker
    working_directory: ~/repo  # Specify your working directory

jobs:
  install_dependencies:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            echo "Installing dependencies on EC2 instance..."
            echo "$EC2_PRIVATE_KEY" > nexus-app.pem
            chmod 600 nexus-app.pem
            cat nexus-app.pem
            ssh -o StrictHostKeyChecking=no -i nexus-app.pem ubuntu@$EC2_PUBLIC_IP "bash -c '
            curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
            sudo apt install -y nodejs'
            "

  deploy:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: SSH into EC2 and deploy
          command: |
            echo "$EC2_PRIVATE_KEY" > nexus-app.pem
            chmod 600 nexus-app.pem
            nexus-app.pem
            ssh -i nexus-app.pem ubuntu@$EC2_PUBLIC_IP 'bash -s' < ./deploy.sh

workflows:
  version: 2
  deploy:
    jobs:
      - install_dependencies:
          filters:
            branches:
              only:
                - main  # This ensures that the `install_dependencies` job runs only on `main`
      - deploy:
          requires:
            - install_dependencies
          filters:
            branches:
              only:
                - main  # This ensures that the `deploy` job runs only on `main`
