version: 2.1

executors:
  node-executor:
    machine:
      enabled: true  # Use CircleCI's default VM, no Docker
    working_directory: ~/repo  # Specify your working directory

jobs:
  install_dependencies:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            echo "Installing dependencies on EC2 instance..."
            ssh ubuntu@$EC2_PUBLIC_IP "bash -c '
            curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
            sudo apt install -y nodejs
            sudo apt install -y nginx'
            "

  deploy:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: SSH into EC2 and deploy
          command: |
            ssh ubuntu@$EC2_PUBLIC_IP "export GITHUB_USERNAME=$GITHUB_USERNAME && export GITHUB_TOKEN=$GITHUB_TOKEN && bash -s" < ./deploy.sh

  run:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Nginx Configuration
          command: |
            ssh ubuntu@$EC2_PUBLIC_IP "bash -s" < ./nginx.sh


workflows:
  version: 2
  deploy:
    jobs:
      - install_dependencies:
          filters:
            branches:
              only:
                - main
      - deploy:
          requires:
            - install_dependencies
          filters:
            branches:
              only:
                - main  # This ensures that the `deploy` job runs only on `main`

      - run:
          requires:
            - install_dependencies
            - deploy
          filters:
            branches:
              only:
                - main  # This ensures that the `deploy` job runs only on `main`
