import { TClient } from './TClient';
import { TCustomer } from './TCustomer';

export type Role = 'ADMIN' | 'CUSTOMER';

export const USER_ROLES: {
  [key: string]: Role;
} = {
  ADMIN: 'ADMIN',
  CUSTOMER: 'CUSTOMER',
};

export type TUser = {
  id?: string;
  email: string;
  password: string;
  fullName: string;
  businessName: string;
  logo?: string;
  brandColor?: string;
  role: Role; // role of the user
  hasFinishedSignup?: boolean; // indicates if the user has finished the setup

  active?: boolean; // indicates if the user is currently active
  lastReport?: string; // date of the last report generated by the user
  customers?: TCustomer[]; // customers that belong to this user
  clients?: TClient[]; // clients that belong to this user
  numberOfGeneratedReports?: number; // number of reports generated by this user
  invoices?: string[]; // array of invoice IDs associated with the user
};
